<html><body><table cellpadding="0" cellspacing="0" width="100%" bgcolor="#ffffff" style="background-color:#ffffff"><tbody><tr><td align="center" style="text-align:left"><table align="center" cellpadding="0" cellspacing="0" id="topMessageWrapper" style="background-color:#ffffff;color:#424242;font-family:'Trebuchet MS';font-size:12px;width:600px;margin:0 auto;" bgcolor="#ffffff" width="600"><tbody><tr><td>
<table border="0" cellspacing="0" cellpadding="0" width="600" height="100%"><tbody><tr><td valign="top" width="400" style="color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<table border="0" cellspacing="0" cellpadding="0" width="100%" height="100%"><tbody><tr><td height="100%" valign="top" style="color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<div style="display: block">
<table cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:0px;padding-left:0px;padding-right:0px;border-top:transparent 0px;border-right:transparent 0px;padding-top:0px;color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;">&nbsp;</p>
<p style="text-align:center;margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;" data-icontact-image-nowrap="true"><img style="border-bottom: transparent 0px solid; border-left: transparent 0px solid; margin: 0px; width: 253px; height: 116px; border-top: transparent 0px solid; border-right: transparent 0px solid" alt="" src="http://staticapp.icpsc.com/icp/loadimage.php/mogile/981640/12c3072e31eb7172c04301fb735bf4fe/image/png" width="253" height="116"></p></td></tr></tbody></table></div></td></tr></tbody></table></td>
<td style="border-bottom:transparent 0px;border-left:transparent 0px;background-color:#c5af7d;border-top:transparent 0px;border-right:transparent 0px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" valign="top" width="200" bgcolor="#c5af7d">
<table border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" valign="top">
<div style="display: block">
<table border="0" cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:40px;background-color:#c5af7d;padding-left:20px;padding-right:20px;border-top:transparent 0px;border-right:transparent 0px;padding-top:31px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" bgcolor="#c5af7d">
<p style="text-align:center;margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="font-family: tahoma, geneva, sans-serif"><span style="color: #ffffff"><span style="font-size: 24px">Newsletter Summer 2011</span></span></span></p></td></tr></tbody></table></div></td></tr></tbody></table></td></tr><tr><td valign="top" width="400" style="color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<table border="0" cellspacing="0" cellpadding="0" width="100%" height="100%"><tbody><tr><td valign="top" style="color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<div>
<table border="0" cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="display:table-cell;color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><img style="border-bottom: transparent 0px solid; border-left: transparent 0px solid; margin: 0px; width: 400px; float: right; height: 179px; border-top: transparent 0px solid; border-right: transparent 0px solid" alt="" src="http://staticapp.icpsc.com/icp/loadimage.php/mogile/981640/46ac8f3196ab3344e84dbf3112b9d333/image/gif" width="400" align="right" height="179"></p></td></tr></tbody></table></div></td></tr></tbody></table></td>
<td style="border-bottom:transparent 0px;border-left:transparent 0px;background-color:#c5af7d;border-top:transparent 0px;border-right:transparent 0px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" valign="top" width="200" bgcolor="#c5af7d">
<table border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" valign="top">
<div>
<table border="0" cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:58px;background-color:#002f5d;padding-left:0px;padding-right:2px;border-top:transparent 0px;border-right:transparent 0px;padding-top:61px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" bgcolor="#002f5d">
<p style="text-align:center;margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="font-family: tahoma, geneva, sans-serif"><span style="color: #ffffff"><span style="font-size: 25px">Go Forth to Serve..</span></span></span></p></td></tr></tbody></table></div></td></tr></tbody></table></td></tr><tr><td valign="top" width="400" style="color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<table border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td valign="top" style="color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<div style="border-color: #c2d9e7;" class="">
<table border="0" cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="padding-bottom:15px;padding-left:15px;padding-right:15px;padding-top:15px;border-top:0px none transparent;border-right:0px none transparent;border-bottom:0px none transparent;border-left:0px none transparent;color:#424242;font-family:'Trebuchet MS';font-size:12px;"><p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;">
	<span style="color: #999999"><span style="font-size: 18px">Welcome,</span></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;">
	<img alt="" src="http://staticapp.icpsc.com/icp/loadimage.php/mogile/981640/94f01702b0ab0cc8892ceb65ac378542/image/png" style="border-bottom: #e0e0e0 4px solid; border-left: #e0e0e0 4px solid; margin: 0px; width: 100px; float: right; height: 98px; border-top: #e0e0e0 4px solid; border-right: #e0e0e0 4px solid" width="100" align="right" height="98">The BYU Chemical Engineering Alumni&nbsp;Society and the BYU Department of Chemical Engineering are teaming up to streamline our communications with our outstanding alumni.&nbsp; We will be sending out an emailed newsletter 3 times a year to keep you up-to-date with the exciting developments in our program.</p>
</td></tr></tbody></table></div>
<div style="display: block">
<table border="0" cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:15px;padding-left:15px;padding-right:15px;border-top:transparent 0px;border-right:transparent 0px;padding-top:15px;color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="color: #999999"><span style="font-size: 18px">Upcoming Events</span></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="font-size: 14px">October 7<sup>th</sup>@ 6 pm -&nbsp;<strong>Annual Alumni Banquet&nbsp;</strong></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="font-size: 12px">&nbsp;&nbsp;&nbsp;&nbsp;Location: BYU Wilkinson Center Rm&nbsp;3220</span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="font-size: 12px">&nbsp;&nbsp;&nbsp;&nbsp;Cost: Free; RSVP to <a href="mailto:serena@byu.edu" style="color:#55aadd!important;"><span style="color: #002f5d">serena@byu.edu</span></a></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="font-size: 14px">September&nbsp;1<sup>st</sup> @ 3-5 pm - <strong>Dr. Rowley's Last Lecture</strong></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="font-size: 12px">&nbsp;&nbsp;&nbsp;&nbsp;Location: BYU, Clyde Rm 254 (3 pm refreshments, 4 pm lecture)</span></p></td></tr></tbody></table></div>
<div>
<table cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:15px;padding-left:0px;padding-right:15px;border-top:transparent 0px;border-right:transparent 0px;padding-top:15px;color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="color: #999999"><span style="font-size: 18px">&nbsp;&nbsp;&nbsp;Department News </span></span></p>
<ul><li><img style="border-bottom: #e0e0e0 4px solid; border-left: #e0e0e0 4px solid; margin: 0px; width: 101px; float: right; height: 101px; border-top: #e0e0e0 4px solid; border-right: #e0e0e0 4px solid" alt="" src="http://staticapp.icpsc.com/icp/loadimage.php/mogile/981640/281a795868f0d6792088e5c3b5932673/image/gif" width="101" height="101" align="right"><strong><a href="http://chemicalengineering.byu.edu/people/richard-l-rowley" style="color:#55aadd!important;"><span style="color: #002f5d">Dr. Richard Rowley</span></a>&nbsp;</strong>is retiring and will be missed.</li>
<li><strong><a href="http://chemicalengineering.byu.edu/people/john-hedengren" style="color:#55aadd!important;"><span style="color: #002f5d">Dr. John Hedengren</span></a>&nbsp;&nbsp;</strong>is starting as&nbsp;a new assistant professor. <a href="http://chemicalengineering.byu.edu/" style="color:#55aadd!important;"><span style="color: #002f5d">Read more..</span></a></li>
<li>The&nbsp;<strong>Global Engineering Outreach </strong>club&nbsp;recently completed a humanitarian trip to Peru.</li>
<li>The&nbsp;<strong>&nbsp;Weidman Center for Global Leadership</strong>&nbsp;was <a href="http://news.byu.edu/archive11-mar-weidman.aspx" style="color:#55aadd!important;"><span style="color: #002f5d">announced</span></a>.</li></ul></td></tr></tbody></table></div>
<div>
<table border="0" cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:15px;padding-left:15px;padding-right:15px;border-top:transparent 0px;border-right:transparent 0px;padding-top:15px;color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="color: #999999"><span style="font-size: 18px">Help a Student get a job in 30 min....</span></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><img style="border-bottom: #e0e0e0 4px solid; border-left: #e0e0e0 4px solid; margin: 0px; width: 99px; float: right; height: 87px; border-top: #e0e0e0 4px solid; border-right: #e0e0e0 4px solid" alt="" src="http://staticapp.icpsc.com/icp/loadimage.php/mogile/981640/2335bb4c8ced9e04b30bd7ae4b5cfdbf/image/gif" width="99" height="87" align="right">Our students have asked for help in developing strong job interview skills.&nbsp; Volunteer to&nbsp;mock interview our students&nbsp;via phone or&nbsp;skype&nbsp;by&nbsp;emailing Dr. Bundy at <a href="mailto:bundy@byu.edu" style="color:#55aadd!important;"><span style="color: #002f5d">bundy@byu.edu</span></a>.</p></td></tr></tbody></table></div>
<div>
<table cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:15px;padding-left:15px;padding-right:15px;border-top:transparent 0px;border-right:transparent 0px;padding-top:15px;color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="color: #999999"><span style="font-size: 18px">Nominate an Outstanding ChE Alumnus....</span></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;">Please take a moment right now and email&nbsp;us at&nbsp;<a href="mailto:tmildnhl@kcc.com" style="color:#55aadd!important;"><span style="color: #002f5d">tmildnhl@kcc.com</span></a>&nbsp;the name of a colleague for&nbsp;the&nbsp;award.</p></td></tr></tbody></table></div>
<div style="display: block">
<table cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:15px;padding-left:15px;padding-right:15px;border-top:transparent 0px;border-right:transparent 0px;padding-top:15px;color:#424242;font-family:'Trebuchet MS';font-size:12px;">
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="color: #999999"><span style="font-size: 18px">Keep in Touch...</span></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><img style="border-bottom: transparent 3px solid; border-left: transparent 3px solid; margin: 0px; width: 100px; float: right; height: 47px; border-top: transparent 3px solid; border-right: transparent 3px solid" alt="" src="http://staticapp.icpsc.com/icp/loadimage.php/mogile/981640/6e79743409b2acc7aeccae5457010daf/image/png" width="100" align="right" height="47">For up-to-date messages, job opportunities, and reminiscing about the good old days&nbsp;at BYU&nbsp;join our Linkedin Group: <span style="color: #212a1a"><strong><a href="http://www.linkedin.com/groups?home=&amp;gid=144032" style="color:#55aadd!important;"><span style="color: #55aadd"><span style="color: #002f5d">BYU Chemical Engineering Alumni</span></span></a></strong></span></p></td></tr></tbody></table></div></td></tr></tbody></table></td>
<td style="border-bottom:transparent 0px;border-left:transparent 0px;background-color:#c5af7d;border-top:transparent 0px;border-right:transparent 0px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" height="100%" valign="top" width="200" bgcolor="#c5af7d">
<table border="0" cellspacing="0" cellpadding="0" width="100%" height="100%"><tbody><tr><td style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" height="100%" valign="top">
<div>
<table border="0" cellspacing="0" cellpadding="0" width="100%" style="word-wrap:break-word;table-layout:fixed;"><tbody><tr><td style="border-bottom:transparent 0px;border-left:transparent 0px;padding-bottom:20px;background-color:#c5af7d;padding-left:20px;padding-right:20px;border-top:transparent 0px;border-right:transparent 0px;padding-top:20px;color:#424242;font-family:'Trebuchet MS';font-size:12px;" bgcolor="#c5af7d">
<p style="text-align:center;margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="font-size: 18px"><span style="color: #212a1a">Thank You for Your Contribution!!</span></span></p>
<p style="text-align:center;margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;">&nbsp;</p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="color: #435434">Your contributions to the department makes a difference in the lives of our students.<span style="color: #002f5d">&nbsp; </span><a href="https://secure3.convio.net/ldsp/site/Donation2?df_id=3320&amp;3320.donation=form1&amp;cid=ProvoENGChem" style="color:#55aadd!important;"><span style="color: #002f5d">Click here to donate now.</span></a><span style="color: #002f5d">&nbsp; </span></span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;">&nbsp;</p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="color: #435434">Be sure to take advantage of corporate matches.&nbsp; To&nbsp;find out&nbsp;if your employer will match your donation&nbsp;<a href="http://www.ldsphilanthropies.org/byu/employer-matching.html" style="color:#55aadd!important;"><span style="color: #002f5d">click here</span></a><span style="color: #002f5d">.</span></span><span style="color: #435434">&nbsp;</span></p>
<p style="margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;">&nbsp;</p>
<p style="text-align:center;margin-bottom:0;margin-left:0;margin-right:0;margin-top:0;padding:0;"><span style="color: #000000"><span style="font-size: 16px">Thank You!</span></span></p></td></tr></tbody></table></div></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></body></html>